[package]
name = "strolle-drawing-shader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
# Workspace
strolle-models = { path = "../../strolle-models" }

# Crates.io
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu" }
