[package]
name = "strolle-indirect-resolving-shader"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["dylib"]

[dependencies]
# Workspace
strolle-gpu = { path = "../../strolle-gpu" }

# Crates.io
spirv-std = { git = "https://github.com/EmbarkStudios/rust-gpu" }
